name: Hyperledger Dev Network Test Pipeline

on:
  push:
    branches:
      - '**feature**'
      - '**fix**'
      - develop
      - master
  pull_request:
    branches: 
      - develop
      - master

jobs:

  DeployAndTestQueryAccess:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: check out source repository
      uses: actions/checkout@v2
    
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # set up Dev_network
    - name: Set up dev_network - dockers
      run: |
        echo "##########################"
        echo "#  start network script  #"
        echo "##########################"
        ./startNetwork.sh feature/private_data &
        echo "##########################"
        echo "# started network script #"
        echo "##########################"
        echo "#    begin sleep         #"
        echo "##########################"
        sleep 180
        echo "#    finish sleep        #"
        echo "##########################"
    
    # run single_query_test
    - name: Run tests
      run: |
        pushd ./tests
        echo "##########################"
        echo "#    starting test       #"
        echo "##########################"
        ./test_access.sh
        echo "##########################"
        echo "#    finished test       #"
        echo "##########################"
        popd
